# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy dotnet core project to Azure Function App - vfkplzintegpuss

on:
  release:
    types: [published]
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-az-app-service-dotnet:
    uses: vestfoldfylke/shared/.github/workflows/deploy-az-app-service-dotnet.yml@main
    with:
      azure_appname: "vfkplzintegpuss" # required
      azure_functionapp_package_path: "pureservice-dotnet" # required. set to path project path. if multiple projects exists in same solution, set this to the project to deploy
      dotnet_version: "9.0.x" # required and must follow the TargetFramework version set in the project file (*.csproj)
    secrets:
      azure_publishprofile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_PROD }}
